#!/usr/bin/env python3
"""
zerodha_get_access_token.py

Independent helper to obtain a Zerodha Kite Connect access token.

Requirements:
    pip install kiteconnect

What it does:
1. Reads API key from environment or prompts for it.
2. Reads API secret securely (hidden input) unless provided in environment.
3. Opens the official Kite Connect login URL in your browser.
4. You log in manually.
5. Paste either:
     - the full redirect URL, or
     - only the request_token
6. Exchanges the one-time request_token for an access_token.
7. Saves a small environment file that TradeMonitor can use.

Security:
- API secret is NOT written to disk by this script.
- The generated access token IS a sensitive credential.
"""

import argparse
import getpass
import os
import sys
import webbrowser
from pathlib import Path
from urllib.parse import parse_qs, urlparse

try:
    from kiteconnect import KiteConnect
    from kiteconnect.exceptions import KiteException
except ImportError:
    print("ERROR: kiteconnect is not installed.")
    print("Install it with:")
    print('    pip install kiteconnect')
    sys.exit(1)


def extract_request_token(value: str) -> str:
    """Accept either a full redirect URL or a raw request_token."""
    value = value.strip()

    if not value:
        raise ValueError("No request_token or redirect URL was provided.")

    # Full URL pasted from browser.
    if "://" in value or "request_token=" in value:
        try:
            parsed = urlparse(value)
            params = parse_qs(parsed.query)
            tokens = params.get("request_token")
            if tokens and tokens[0]:
                return tokens[0].strip()
        except Exception:
            pass

        # Also handle a copied query-string fragment.
        if "request_token=" in value:
            fragment = value.split("request_token=", 1)[1]
            return fragment.split("&", 1)[0].strip()

        raise ValueError(
            "Could not find request_token in the pasted redirect URL."
        )

    # Assume user pasted only the token.
    return value


def save_env_file(path: Path, api_key: str, access_token: str) -> None:
    content = (
        "# Generated by zerodha_get_access_token.py\n"
        "# Treat this file as a secret. Do not commit it to Git.\n"
        f"ZERODHA_API_KEY={api_key}\n"
        f"ZERODHA_ACCESS_TOKEN={access_token}\n"
    )

    path.write_text(content, encoding="utf-8")

    # Best effort: owner read/write only on Unix-like systems.
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def mask(token: str) -> str:
    if len(token) <= 8:
        return "*" * len(token)
    return token[:4] + ("*" * max(4, len(token) - 8)) + token[-4:]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Zerodha Kite Connect access token."
    )
    parser.add_argument(
        "--output",
        default="zerodha_access.env",
        help="File in which API key and access token will be saved "
             "(default: zerodha_access.env)",
    )
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Print the login URL but do not open a browser automatically.",
    )
    parser.add_argument(
        "--show-token",
        action="store_true",
        help="Also display the complete access token in the terminal.",
    )
    args = parser.parse_args()

    print("=" * 64)
    print("ZERODHA KITE CONNECT - ACCESS TOKEN GENERATOR")
    print("=" * 64)
    print()
    print("This program does NOT automate your Zerodha login.")
    print("You will log in manually in the official Zerodha browser page.")
    print()

    api_key = os.getenv("ZERODHA_API_KEY", "").strip()
    if not api_key:
        api_key = input("Zerodha API key: ").strip()

    if not api_key:
        print("ERROR: API key is required.")
        return 2

    api_secret = os.getenv("ZERODHA_API_SECRET", "").strip()
    if not api_secret:
        api_secret = getpass.getpass(
            "Zerodha API secret (input hidden; not saved): "
        ).strip()

    if not api_secret:
        print("ERROR: API secret is required.")
        return 2

    kite = KiteConnect(api_key=api_key)
    login_url = kite.login_url()

    print()
    print("1. Open/login at this official Zerodha URL:")
    print()
    print(login_url)
    print()

    if not args.no_browser:
        try:
            opened = webbrowser.open(login_url)
            if opened:
                print("Browser opened.")
            else:
                print("Could not open the browser automatically; use the URL above.")
        except Exception:
            print("Could not open the browser automatically; use the URL above.")

    print()
    print("2. Complete Zerodha login manually.")
    print("3. Zerodha will redirect to the Redirect URL configured for your app.")
    print("4. Copy the ENTIRE URL from the browser address bar.")
    print("   It should contain: request_token=...")
    print()
    pasted = input(
        "Paste the full redirect URL (or only request_token) here:\n> "
    )

    try:
        request_token = extract_request_token(pasted)
    except ValueError as exc:
        print(f"ERROR: {exc}")
        return 2

    print()
    print("Exchanging request_token for access_token...")

    try:
        session = kite.generate_session(
            request_token=request_token,
            api_secret=api_secret,
        )
    except KiteException as exc:
        print()
        print(f"ZERODHA ERROR: {exc}")
        print()
        print("Most common causes:")
        print("- request_token has expired")
        print("- request_token was already used once")
        print("- API key/API secret do not belong to the same Kite Connect app")
        print("- the wrong value was copied from the redirect URL")
        return 3
    except Exception as exc:
        print(f"ERROR: {type(exc).__name__}: {exc}")
        return 3

    access_token = session.get("access_token")
    if not access_token:
        print("ERROR: Zerodha response did not contain an access_token.")
        return 3

    # Verify that the token actually works, using a harmless read call.
    kite.set_access_token(access_token)
    try:
        profile = kite.profile()
    except Exception as exc:
        print(f"ERROR: Token was generated, but profile verification failed: {exc}")
        return 4

    output_path = Path(args.output).expanduser().resolve()
    save_env_file(output_path, api_key, access_token)

    print()
    print("=" * 64)
    print("SUCCESS")
    print("=" * 64)
    print(f"Verified Zerodha user: {profile.get('user_id', '(unknown)')}")
    print(f"Access token: {mask(access_token)}")
    print(f"Saved to: {output_path}")
    print()

    if args.show_token:
        print("Full access token:")
        print(access_token)
        print()

    print("For TradeMonitor, use:")
    print(f"    ZERODHA_API_KEY={api_key}")
    print("    ZERODHA_ACCESS_TOKEN=<value from zerodha_access.env>")
    print()
    print("Do NOT commit zerodha_access.env to Git.")
    print("Do NOT share the API secret or access token.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
